apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -c -o deploy/kubechat
    kompose.version: 1.26.0 (40646f47)
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
  name: celeryworker
spec:
  replicas: {{ index .Values "celery-worker" "replicaCount" }}
  selector:
    matchLabels:
      {{- include "kubechat.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubechat.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - /app/scripts/start-celery-worker.sh
          env:
            - name: AUTH0_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: AUTH0_CLIENT_ID
                  name: docker-env
            - name: AUTH0_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: AUTH0_DOMAIN
                  name: docker-env
            - name: AUTH_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: AUTH_ENABLED
                  name: docker-env
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: CELERY_BROKER_URL
                  name: docker-env
            - name: CELERY_FLOWER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_PASSWORD
                  name: docker-env
            - name: CELERY_FLOWER_USER
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_USER
                  name: docker-env
            - name: DJANGO_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_LOG_LEVEL
                  name: docker-env
            - name: MEMORY_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: MEMORY_REDIS_URL
                  name: docker-env
            - name: MODEL_SERVER
              valueFrom:
                configMapKeyRef:
                  key: MODEL_SERVER
                  name: docker-env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: docker-env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: docker-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: docker-env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: docker-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: docker-env
            - name: VECTOR_DB_CONTEXT
              valueFrom:
                configMapKeyRef:
                  key: VECTOR_DB_CONTEXT
                  name: docker-env
            - name: VECTOR_DB_TYPE
              valueFrom:
                configMapKeyRef:
                  key: VECTOR_DB_TYPE
                  name: docker-env
          image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: kubechat-celeryworker
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {}
      restartPolicy: Always
status: {}
