apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -c -o deploy/kubechat
    kompose.version: 1.26.0 (40646f47)
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
  name: django
spec:
  replicas: {{ .Values.django.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubechat.selectorLabels" . | nindent 6 }}
      {{- include "django.labels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubechat.selectorLabels" . | nindent 8 }}
        {{- include "django.labels" . | nindent 8 }}
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - |
              ln -s /data/torch /root/.cache/torch
              /app/scripts/entrypoint.sh /app/scripts/start-django.sh
          env:
            - name: AUTH0_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: AUTH0_CLIENT_ID
                  name: kubechat-config
            - name: AUTH0_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: AUTH0_DOMAIN
                  name: kubechat-config
            - name: AUTH_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: AUTH_ENABLED
                  name: kubechat-config
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: CELERY_BROKER_URL
                  name: kubechat-config
            - name: CELERY_FLOWER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_PASSWORD
                  name: kubechat-config
            - name: CELERY_FLOWER_USER
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_USER
                  name: kubechat-config
            - name: DJANGO_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_LOG_LEVEL
                  name: kubechat-config
            - name: MEMORY_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: MEMORY_REDIS_URL
                  name: kubechat-config
            - name: MODEL_SERVER
              valueFrom:
                configMapKeyRef:
                  key: MODEL_SERVER
                  name: kubechat-config
            - name: MODEL_SERVERS
              valueFrom:
                configMapKeyRef:
                  key: MODEL_SERVERS
                  name: kubechat-config
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: kubechat-config
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: kubechat-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: kubechat-config
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: kubechat-config
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: kubechat-config
            - name: VECTOR_DB_CONTEXT
              valueFrom:
                configMapKeyRef:
                  key: VECTOR_DB_CONTEXT
                  name: kubechat-config
            - name: VECTOR_DB_TYPE
              valueFrom:
                configMapKeyRef:
                  key: VECTOR_DB_TYPE
                  name: kubechat-config
            - name: OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: OPENAI_API_KEY
                  name: kubechat-config
            - name: MEDIA_ROOT
              value: /data/media
          image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: kubechat-django
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kubechat-efs-claim
