apiVersion: v1
data:
  AUTH_ENABLED: "{{ .Values.django.authEnabled }}"
  AUTH0_CLIENT_ID: {{ .Values.django.auth0ClientId }}
  AUTH0_DOMAIN: {{ .Values.django.auth0Domain }}
  CELERY_BROKER_URL: {{ index .Values "celery-worker" "brokerURL" }}
  CELERY_FLOWER_USER: {{ .Values.flower.user }}
  CELERY_FLOWER_PASSWORD: {{ .Values.flower.password }}
  DJANGO_LOG_LEVEL: "INFO"
  MEMORY_REDIS_URL: {{ .Values.django.memoryRedisURL }}
  MODEL_SERVER: {{ .Values.django.modelServer }}
  MODEL_SERVERS: '{{ .Values.django.modelServers }}'
  POSTGRES_DB: {{ .Values.django.metaDBDatabase }}
  POSTGRES_HOST: {{ .Values.django.metaDBHost }}
  POSTGRES_PORT: "{{ .Values.django.metaDBPort}}"
  POSTGRES_USER: {{ .Values.django.metaDBUser }}
  POSTGRES_PASSWORD: {{ .Values.django.metaDBPassword }}
  VECTOR_DB_CONTEXT: '{{ .Values.django.vectorDBContext }}'
  VECTOR_DB_TYPE: {{ .Values.django.vectorDBType }}
  OPENAI_API_KEY: {{ .Values.django.openaiAPIKey }}
  EMBEDDING_PRE_LOAD: "{{ .Values.django.embeddingPreLoad }}"
kind: ConfigMap
metadata:
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
  name: kubechat-config
