apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -c -o deploy/kubechat
    kompose.version: 1.26.0 (40646f47)
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
    {{- include "django.labels" . | nindent 4 }}
  name: kubechat
spec:
  ports:
    - name: "80"
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    {{- include "kubechat.selectorLabels" . | nindent 4 }}
    {{- include "django.labels" . | nindent 4 }}
