[tool.poetry]
name = "kubechat"
version = "0.1.0"
description = "A LLM based tool to support Text2SQL, Chatbot, KubeBlocks pilot and troubleshooting"
authors = ["nayutah <dullboy@apecloud.com>"]
readme = "README.md"
packages = [{include = "server"}]

[tool.poetry.dependencies]
python = "==3.11.3"
langchain = "^0.0.206"
llama-index = "^0.6.29"
uvicorn = "^0.22.0"
django = "^4.2.2"
fastapi = "^0.97.0"
transformers = "^4.30.2"
torch = {version = ">=1,<3", optional = true}
pydantic = "^1.10.9"
sqlalchemy = "^2.0.16"
sqlparse = "^0.4.4"
llama-hub = "^0.0.3"
auto-gpt-plugin-template = "^0.0.3"
nltk = "^3.8.1"
pymysql = "^1.0.3"
cryptography = "^41.0.1"
gpt4all = "^0.3.5"
python-dotenv = "^1.0.0"
django-environ = "^0.10.0"
django-ninja = "^0.22.2"
requests = "^2.31.0"
auth0-python = "^4.2.0"
qdrant-client = "^1.3.0"
celery = "^5.3.1"
channels = "^4.0.0"
sentence-transformers = "^2.2.2"
pymilvus = "^2.2.12"
pypdf = "^3.11.0"
clickhouse-connect = "^0.6.4"
chromadb = "^0.3.26"
daphne = "^4.0.0"
docx2txt = "^0.8"
redis = "^4.6.0"
pymongo = "^4.4.0"
elasticsearch = "^8.8.0"
weaviate-client = "^3.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "server.main:start"
llmserver = "server.llmserver:start"
webserver = "server.webserver:start"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
