[tool.poetry]
name = "kubechat"
version = "0.1.0"
description = "A LLM based tool to support Text2SQL, Chatbot, KubeBlocks pilot and troubleshooting"
authors = ["nayutah <dullboy@apecloud.com>"]
readme = "README.md"
packages = [{include = "server"}]

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.0.206"
llama-index = "^0.6.29"
uvicorn = "^0.22.0"
django = "^4.2.2"
fastapi = "^0.97.0"
transformers = "^4.30.2"
torch = {url = "https://download.pytorch.org/whl/cpu/torch-2.0.1-cp311-none-macosx_11_0_arm64.whl"}
pydantic = "^1.10.9"
requests = "^2.31.0"
sqlalchemy = "^2.0.16"
sqlparse = "^0.4.4"
llama-hub = "^0.0.3"
auto-gpt-plugin-template = "^0.0.3"
nltk = "^3.8.1"
pymysql = "^1.0.3"
cryptography = "^41.0.1"
gpt4all = "^0.3.5"
gradio = "^3.35.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "server.main:start"
llmserver = "server.llmserver:start"
webserver = "server.webserver:start"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
