{{- range .Values.models }}
{{- $rangeItem := . -}}
{{- with $ }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llmserver.fullname" . }}-{{ $rangeItem.name }}
  labels:
    {{- include "llmserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "llmserver.selectorLabels" . | nindent 4 }}
    chat.kubeblocks.io/model-name: {{ $rangeItem.name }}
{{- end }}
{{- end }}
