apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -c -o deploy/aperag
    kompose.version: 1.26.0 (40646f47)
  labels:
    {{- include "aperag.labels" . | nindent 4 }}
  name: celeryworker
spec:
  replicas: {{ index .Values "celery-worker" "replicaCount" }}
  selector:
    matchLabels:
      {{- include "aperag.selectorLabels" . | nindent 6 }}
      {{- include "celeryworker.labels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aperag.selectorLabels" . | nindent 8 }}
        {{- include "celeryworker.labels" . | nindent 8 }}
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - |
              mkdir -p /data/.cache
              mkdir -p /root/.cache
              ln -s /data/.cache/huggingface /root/.cache/
              ln -s /data/.cache/torch /root/.cache/
              /app/scripts/entrypoint.sh /app/scripts/start-celery-worker.sh
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: aperag-celeryworker
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with index .Values "celery-worker" "resources" }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /data
              name: data
            - name: env-config
              mountPath: /app/env-config
              readOnly: true
      restartPolicy: Always
      {{- with index .Values "celery-worker" "affinity" }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        # shared uploaded files between django and celery
        - name: data
          hostPath:
            path: {{ .Values.django.dataPath }}
        - name: env-config
          secret:
            secretName: aperag-env
