apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -c -o deploy/aperag
    kompose.version: 1.26.0 (40646f47)
  labels:
    {{- include "aperag.labels" . | nindent 4 }}
  name: flower
spec:
  replicas: {{ .Values.flower.replicaCount }}
  selector:
    matchLabels:
      {{- include "aperag.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aperag.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - |
              /app/scripts/entrypoint.sh /app/scripts/start-celery-flower.sh
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: aperag-flower
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5555
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: env-config
              mountPath: /app/config
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: env-config
          secret:
            secretName: aperag-env
status: {}
