apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -c -o deploy/aperag
    kompose.version: 1.26.0 (40646f47)
  labels:
    {{- include "aperag.labels" . | nindent 4 }}
  name: flower
spec:
  replicas: {{ .Values.flower.replicaCount }}
  selector:
    matchLabels:
      {{- include "aperag.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aperag.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - |
              /app/scripts/entrypoint.sh /app/scripts/start-celery-flower.sh
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: aperag-flower
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5555
          env:
            - name: POSTGRES_HOST
              value: {{ include "database.postgresHost" . | quote }}
            - name: POSTGRES_PORT
              value: {{ include "database.postgresPort" . | quote }}
            - name: POSTGRES_DB
              value: {{ include "database.postgresDB" . | quote }}
            - name: POSTGRES_USER
              value: {{ include "database.postgresUser" . | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ include "database.postgresPassword" . | quote }}
            - name: DATABASE_URL
              value: {{ include "database.databaseUrl" . | quote }}
            - name: CELERY_BROKER_URL
              value: {{ include "database.celeryBrokerUrl" . | quote }}
            - name: MEMORY_REDIS_URL
              value: {{ include "database.memoryRedisUrl" . | quote }}
            - name: ES_HOST # This will now be generated by the helper, including protocol and port
              value: {{ include "database.esHost" . | quote }}
          resources:
            {{- toYaml .Values.flower.resources | nindent 12 }}
          volumeMounts:
            - name: env-config
              mountPath: /app/env-config
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: env-config
          secret:
            secretName: aperag-env
status: {}
