apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -c -o deploy/aperag
    kompose.version: 1.26.0 (40646f47)
  labels:
    {{- include "aperag.labels" . | nindent 4 }}
  name: aperag-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "aperag.selectorLabels" . | nindent 4 }}
    {{- include "frontend.labels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: aperag-console
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 80
  selector:
    app: aperag-console
  type: {{ .Values.service.type }}
