name: Release Image

on:
  workflow_call:
    inputs:
      VERSION:
        type: string
        description: 'The tag name of image'
        required: false
        default: ''
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'The tag name of image'
        required: true
        default: ''
  push:
    branches: [ main ]


jobs:
  image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.get_tag_name.outputs.tag_name }}
    steps:
      - name: Get Tag Name
        id: get_tag_name
        run: |
          TAG_NAME=${{ inputs.VERSION }}
          if [[ -z "$TAG_NAME" ]]; then
              TAG_NAME=latest
          fi
          echo tag_name=$TAG_NAME >> $GITHUB_OUTPUT

  release-image:
    needs: image-tag
    uses: apecloud/apecloud-cd/.github/workflows/release-image.yml@v0.1.33
    with:
      MAKE_OPS: "docker-build"
      IMG: "apecloud/aperag-console"
      VERSION: "${{ needs.image-tag.outputs.tag-name }}"
      REMOVE_PREFIX: true
    secrets: inherit
