# Global settings applicable to all database clusters
global:
  namespace: "demo" # The namespace where all clusters will be deployed
  terminationPolicy: "Delete" # Common termination policy

postgresql:
  enabled: true
  name: "pg-cluster" # Name for the PostgreSQL cluster
  serviceVersion: "14.7.2"
  disableExporter: false # Corresponds to Kubeblocks disableExporter
  customSecretName:
  customSecretNamespace:
  replicas: 1
  resources:
    limits:
      cpu: "0.5"
      memory: "0.5Gi"
    requests:
      cpu: "0.5"
      memory: "0.5Gi"
  storage: "5Gi"

redis:
  enabled: true
  name: "redis-standalone" # Name for the Redis cluster
  topology: "standalone"   # Explicitly set topology
  serviceVersion: "7.2.4"  # Keep or update as needed
  disableExporter: false   # Keep or update as needed
  customSecretName:
  customSecretNamespace:
  replicas: 1              # Standalone typically means 1 replica
  resources:
    limits:
      cpu: "0.5"
      memory: "0.5Gi"
    requests:
      cpu: "0.5"
      memory: "0.5Gi"
  storage: "5Gi"

elasticsearch:
  enabled: true
  name: "es-cluster" # Name for the Elasticsearch cluster
  # Note: Elasticsearch in Kubeblocks often uses 'componentDef' rather than 'clusterDef' directly in its spec.
  # And 'serviceVersion' is also part of the component.
  # The example provided doesn't have `disableExporter` at the spec level or component level.
  componentDef: "elasticsearch-8" # Example: "elasticsearch-8"
  serviceVersion: "8.8.2"
  replicas: 1 # For the 'mdit' component (or whatever the main ES component is named)
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "1"
      memory: "1Gi"
  storage: "5Gi"
  # Elasticsearch example has specific 'configs'. For simplicity, we'll hardcode the single-node mode as in your example.
  # If more complex configs are needed, this part could be expanded.

qdrant:
  enabled: true
  name: "qdrant-cluster" # Name for the Qdrant cluster
  serviceVersion: "1.10.0"
  disableExporter: false
  replicas: 1
  resources:
    limits:
      cpu: "0.5"
      memory: "0.5Gi"
    requests:
      cpu: "0.5"
      memory: "0.5Gi"
  storage: "5Gi"