django:
  domainName: chat.apecloud.cn
  replicaCount: 2
  embeddingModel: bge
  authType: authing
  authingAppId: "6520eca1907b81f28ef1ffb6"
  authingDomain: "kubechat.authing.cn"
  openaiAPIKey: ""


celery-worker:
  replicaCount: 2