ingress:
  className: alb

django:
  domainName: chat.kubeblocks.io
  replicaCount: 2
  embeddingModel: bge
  authType: auth0
  auth0ClientId: "G6RuQZZNaDorHGUEOv7Mgq1COqfryTB2"
  auth0Domain: "kubechat.jp.auth0.com"
  openaiAPIKey: ""
  resources:
    limits:
      nvidia.com/gpu: "1"

celery-worker:
  replicaCount: 2