apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: bc
spec:
  clusterDefinitionRef: vllm # ref clusterdefinition.name
  clusterVersionRef: vllm-baichuan-13b-local
  terminationPolicy: Delete
  componentSpecs:
  - name: vllm
    componentDefRef: vllm
    monitor: false
    replicas: 2
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
