name: Release Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The tag of image'
        required: true
        default: ''
      image_name:
        description: 'Only release select image'
        required: false
        default: ''
        type: choice
        options:
          - kubechat
          - kubechat-llmserver
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.ref_name }}


run-name: Release Image:${{ inputs.image_name }}:${{ inputs.image_tag }} ${{ github.ref_name }}

jobs:
  image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.get_tag_name.outputs.tag_name }}
    steps:
      - name: Get Tag Name
        id: get_tag_name
        run: |
          TAG_NAME=${{ inputs.image_tag }}
          if [[ -z "$TAG_NAME" ]]; then
              TAG_NAME="${{ env.RELEASE_VERSION }}"
          fi
          echo tag_name=$TAG_NAME >> $GITHUB_OUTPUT

  release-kubechat-image:
    if: ${{ github.event.action == 'published' || inputs.image_name == '' || inputs.image_name == 'kubechat' }}
    needs: [ image-tag ]
    uses: apecloud/apecloud-cd/.github/workflows/release-image-cache.yml@v0.1.34
    with:
      MAKE_OPS_PRE: "build-requirements version"
      IMG: "apecloud/kubechat"
      VERSION: "${{ needs.image-tag.outputs.tag-name }}"
      DOCKERFILE_PATH: "./docker/Dockerfile"
      PYTHON_VERSION: "3.11"
      POETRY_VERSION: "1.6.1"
      REMOVE_PREFIX: false
    secrets: inherit

  release-kubechat-llmserver-image:
    if: ${{ github.event.action == 'published' || inputs.image_name == '' || inputs.image_name == 'kubechat-llmserver' }}
    needs: [ image-tag ]
    uses: apecloud/apecloud-cd/.github/workflows/release-image-cache.yml@v0.1.34
    with:
      MAKE_OPS_PRE: "build-requirements version"
      IMG: "apecloud/kubechat-llmserver"
      VERSION: "${{ needs.image-tag.outputs.tag-name }}"
      DOCKERFILE_PATH: "./docker/Dockerfile-llmserver"
      PYTHON_VERSION: "3.11"
      POETRY_VERSION: "1.6.1"
      REMOVE_PREFIX: false
    secrets: inherit
